[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
std = "c11"
hide-symbols = true
include = ["include"]

[build.cpp]
std = "c++23"
hide-symbols = true
include = ["include"]

[AwdawdAI]
exe = "AwdawdAI"
lang = "cpp"
libs = [ "nwge", "SDL2" ]
